language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install --dev --prefer-source

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
